sudo: false

language: python

python:
  - '2.7'
  - '3.3'

addons:
  apt:
    packages:
      - cython
      - liblapack-dev
      - libhdf5-dev

cache:
  - pip

script:
  - pip install flake8 hacking
  - flake8 .
