sudo: false

language: python

python:
  - '2.7'
  - '3.3'

cache:
  - pip

before_install:
  - sudo apt-get install -qq cython liblapack-dev libhdf5-dev

script:
  - pip install flake8 hacking
  - flake8 .
